name: Pack Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install ZIP
        uses: montudor/action-zip@v1
        
      - name: Setup NPM packages
        run: npm install
        
      - name: Pack extension
        run: npm run build-action

      - name: Build CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          # zip file made at the packExtensionDir step
          zipFilePath: '../OldTwitterChrome.zip'
          crxFilePath: 'OldTwitterChrome.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Upload for Chromium
        uses: actions/upload-artifact@v4
        with:
          name: OldTwitterChrome.crx
          path: ${{ github.workspace }}/OldTwitterChrome.crx
